version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Account
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`     
      - sbt docker   
  post_build:
    commands:
      - echo tagging
      - docker tag mfa:latest 286230295403.dkr.ecr.eu-central-1.amazonaws.com/mfa:latest
      - echo Pushing the Docker image...
      - docker push 286230295403.dkr.ecr.eu-central-1.amazonaws.com/mfa:latest